spring:
  datasource:
    url: jdbc:mysql://localhost:3306/database?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: root1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 393876664195-f66aqj0mmdb8hu9g04pl6aj07bc50k27.apps.googleusercontent.com
            clientSecret: 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
            redirect-uri: '{baseUrl}/oauth2/callback/{registrationId}'
            scope:
              - email
              - profile
          facebook:
            clientId: 850723448696431
            clientSecret: 5ec5252243a3ea0c21d0795509475956
            redirect-uri: '{baseUrl}/oauth2/callback/{registrationId}'
            scope:
              - email
              - public_profile
          github:
            clientId: d3e47fc2ddd966fa4352
            clientSecret: 3bc0f6b8332f93076354c2a5bada2f5a05aea60d
            redirect-uri: '{baseUrl}/oauth2/callback/{registrationId}'
            scope:
              - 'user:email'
              - 'read:user'
        provider:
          facebook:
            authorizationUri: 'https://www.facebook.com/v3.0/dialog/oauth'
            tokenUri: 'https://graph.facebook.com/v3.0/oauth/access_token'
            userInfoUri: >-
              https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    username: mayanktech1606@gmail.com
    password: Iostream*1
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris:
      - 'http://localhost:4200/oauth2/redirect'
      - 'http://localhost:3000/oauth2/redirect'
      - 'myandroidapp://oauth2/redirect'
      - 'myiosapp://oauth2/redirect'
